import { Nunito, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import Nav from "./components/Nav";

const poppins = Poppins({
  weight: ["400", "600", "700"],
  variable: "--font-poppins",
  subsets: ["latin"],
});

const nunito = Nunito({
  weight: ["400", "600", "700"],
  variable: "--font-nunito",
  subsets: ["latin"],
});

export const metadata = {
  title: "Quarter",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${nunito.variable} antialiased`}>
        <Navbar></Navbar>
        <Nav></Nav>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}